package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;
import io.flutter.Log;

import io.flutter.embedding.engine.FlutterEngine;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  private static final String TAG = "GeneratedPluginRegistrant";
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    try {
      flutterEngine.getPlugins().add(new network.particle.authcore_flutter.ParticleAuthCorePlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin particle_auth_core, network.particle.authcore_flutter.ParticleAuthCorePlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new network.particle.base_flutter.ParticleBasePlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin particle_base, network.particle.base_flutter.ParticleBasePlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new network.particle.connect_plugin.ParticleConnectPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin particle_connect, network.particle.connect_plugin.ParticleConnectPlugin", e);
    }
  }
}
